### ISSUE TITLE
Suggestion: WARNING box for reminding users to make a virtual environment before proceeding with Xircuits installation

### ISSUE THREAD

**Issue by yuenherny** [XpressAI/xircuits.io#12]
Making a virtual env before installing packages is a good practice to have, but many users are ignoring it for some reason.

Currently the Xircuits docs has this:
![image](https://user-images.githubusercontent.com/59016908/185085854-cb4c395c-6e74-410c-a159-11f169be9590.png)

Perhaps making that into a WARNING box would be a nice touch to remind users before proceeding, with the following suggested message:

> We recommend installing Xircuits in a virtual environment (see [here](https://docs.python.org/3/library/venv.html) on how to create one) as it might induce dependency issues for other Python projects if you do not do so. See more [here](https://www.geeksforgeeks.org/python-virtual-environment/#:~:text=A%20virtual%20environment%20is%20a,of%20the%20Python%20developers%20use.).

Feel free to change the warning message to suit your context.

**Comment by MFA-X-AI** [comment]
Thanks for the suggestion! I've included it with the 1.5 docs update PR. 😄
